### PR TITLE
Silent option

### PR DESCRIPTION
**Pull request by bcaudan**
Add silent option that allow to execute specs without using terminal reporters.

### CODE REVIEW

**Comment by bcaudan** [comment]
Actually, I need that option because I'm working on another reporter (https://github.com/bcaudan/jasmine-spec-reporter) and I don't want that terminal reporter output messes up with my reporter output when I'm using it with protractor.

**Comment by zemirco** [comment]
+1

See my current tests at [nghellostyle#L742](https://travis-ci.org/zemirco/nghellostyle#L742). The default dots still show up and break the indentation.

**Comment by bcaudan** [comment]
Managing reporters could be a big topic on protractor but this can be a first step to easily add custom console reporter. If this approach does not seems fine, I'll be glad to discuss it with you to find a better way and to help you to implement it.

**Comment by daniellmb** [comment]
+1 I'm interested in using custom reporters as well...

**Comment by mathieubigorne** [comment]
+1 Great Job

**Comment by flegall** [comment]
+1

**Comment by juliemr** [comment]
Sooo the Jasmine 2.0 move changed a lot of stuff underlying this change. Mind rebasing?

**Comment by bcaudan** [comment]
Done!

**Comment by juliemr** [comment]
note: this is done in the Jasmine branch with 0821f58eabbe81b298ad87487901304fec384c87

and released for jasmine1 with v1.1.0

**Pull request closed without merging**
