### PR TITLE
Disable default reporter Jasmine2

### PR DESCRIPTION
**Pull request by razvanz**
Solution for #24.

### CODE REVIEW

**Comment by elgalu** [comment]
You can always modify the PR yourself then `git push --force` to update it.

**Comment by razvanz** [comment]
Ok. I'll do that as soon as I get some time.

**Comment by razvanz** [comment]
There you go. Same style as it was implemented on jasmine1 branch.

**Comment by razvanz** [comment]
Nobody maintaining this project?

**Pull request closed without merging**
