### PR TITLE
Add ddescribe and iit by merging from karma-jasmine

### PR DESCRIPTION
**Pull request by alanmyrvold**
Merge ddescribe and iit from https://github.com/karma-runner/karma-jasmine/blob/master/lib/jasmine.js

### CODE REVIEW

**Comment by facultymatt** [comment]
Whats the status on this? I noticed that as of protractor 0.12.0 this is still not included. Really frustrating since running a whole set of e2e tests takes some time... would be great to add this functionality. @juliemr any chance this can be merged and npm / protractor updated?

**Comment by zolayvar** [comment]
+1, This would be great to have.

**Comment by juliemr** [comment]
Hey folks,

Quick update on the silence from my end (I've spoken with @alanmyrvold but failed to update this PR, which is my mistake). Support for iit and ddescribe is going to be added natively to Jasmine 2.0, which is coming out "very soon" and I plan to migrate minijasminenode to 2.0 as soon as it's officially released. So, I'd been holding off on this so that people wouldn't have to possibly change their tests twice. 

However, as always, "very soon" is not quite as soon as we might like. So, I'm going to take a look at what Jasmine has on github and see if this is compatible, and report back.

**Comment by juliemr** [comment]
Turns out that Jasmine is not actually planning on doing native ddescribe support in 2.0 - just adding easy plug-in framework for this. So, merging this for now, with the disclaimer that things may change when Jasmine 2.0 comes out (but then, things will change anyway). Will release in 0.2.5 asap.

**Pull request merged**
