### PR TITLE
util.print → console.log

### PR DESCRIPTION
**Pull request by danmichaelo**
Same changes as in [jasmine-node/pull/248](//github.com/mhevery/jasmine-node/pull/248)

### CODE REVIEW

**Comment by danmichaelo** [comment]
ping :rabbit:

**Comment by juliemr** [comment]
Hi! Sorry for the silence. Why this change? I do not see util.print as deprecated anywhere - could you please provide a context link? 

For reference, I don't see the 'deprecated' messages, and I'm running node 0.10.22

**Comment by danmichaelo** [comment]
I'm not really into the node project, but I'm using 0.11.9 and got lot's of deprecation warnings. Digging a little bit, it seems like it was deprecated [here](//github.com/joyent/node/commit/896b2aa7).

**Comment by seanmay** [comment]
Any chance this could be merged?

I'm hoping to get a team into a Gulp paradigm, which includes this great little plugin, for unit-testing modular new Angular "widgets", but I know that if we move from 10.26 to 12 (when that does happen), we'll be plagued with "util.print: Use console.log instead", all over the output (as 11.X is doing, currently).  
image

**Comment by juliemr** [comment]
Done!

**Pull request closed without merging**
